name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:2.7.18-buster
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt
    - name: Generate & Upload
      run: |
        cd ci
        ./generate_static_htdocs
        ls ../htdocs
        # lftp -c "open -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER; mirror -R ../htdocs wwwroot/"
